FROM openresty/openresty:focal

# make the 'app' folder the current working directory
WORKDIR /app/src

RUN apt-get update -y

# install debug tools
RUN apt-get install net-tools vim procps -y
# install python3
RUN apt-get install python3 python3-pip -y
# install python libs
RUN pip3 install tornado
