
version: '3.9'

services:
  dev_my_mysql:
    restart: unless-stopped
    image: "mysql:8.0.18"
    container_name: dev_my_mysql
    networks:
      - "dev_networks"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'root'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', "--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    tty: true

  dev_my_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: dev_my_elasticsearch
    environment:
      - node.name=dev-my-es01
      - cluster.name=dev-my-es-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - "dev_networks"

  dev_my_redis:
    restart: unless-stopped
    image: "redis:alpine"
    container_name: dev_my_redis
    networks:
      - "dev_networks"
    ports:
      - "6379:6379"
    tty: true

  dev_my_leveldb:
    image: "ekristen/leveldb:latest"
    container_name: dev_my_leveldb
    ports:
      - "2012:2012"


  dev_my_zoomkeeper:
    restart: unless-stopped
    image: "wurstmeister/zookeeper:latest"
    container_name: dev_my_zoomkeeper
    networks:
      - "dev_networks"
    ports:
      - "2181:2181"

  dev_my_kafka:
    restart: unless-stopped
    image: "wurstmeister/kafka:latest"
    container_name: dev_my_kafka
    depends_on:
      - dev_my_zoomkeeper
    networks:
      - "dev_networks"
    ports:
      - "19092:9092"
    environment:
#      KAFKA_ADVERTISED_HOST_NAME: '0.0.0.0'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://10.91.30.140:19092'
#      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:19092'
      KAFKA_ZOOKEEPER_CONNECT: dev_my_zoomkeeper:2181

  dev_my_mongo:
    restart: unless-stopped
    image: "harbor.ops.qianxin-inc.cn/ateam/mongo:3.4"
    container_name: dev_my_mongo
    networks:
      - "dev_networks"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'root'

networks:
  dev_networks:
    external: true
